# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bang
      POSTGRES_PASSWORD: bang
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../testfiles/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
  bang:
    image: bang
    volumes:
      - testfiles/unpack:/unpack
      - testfiles/:/input
      - src/:/src
      - /tmp:/tmp
    working_dir: /src
