# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResourcesInternal.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ResourcesInternal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Configuration_pb2 as Configuration__pb2
import Resources_pb2 as Resources__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ResourcesInternal.proto\x12\x10\x61\x61pt.pb.internal\x1a\x13\x43onfiguration.proto\x1a\x0fResources.proto\"\x97\x02\n\x0c\x43ompiledFile\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12&\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x16.aapt.pb.Configuration\x12)\n\x04type\x18\x03 \x01(\x0e\x32\x1b.aapt.pb.FileReference.Type\x12\x13\n\x0bsource_path\x18\x04 \x01(\t\x12>\n\x0f\x65xported_symbol\x18\x05 \x03(\x0b\x32%.aapt.pb.internal.CompiledFile.Symbol\x1aH\n\x06Symbol\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12\'\n\x06source\x18\x02 \x01(\x0b\x32\x17.aapt.pb.SourcePositionB\x1a\n\x18\x61ndroid.aapt.pb.internalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ResourcesInternal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030android.aapt.pb.internal'
  _globals['_COMPILEDFILE']._serialized_start=84
  _globals['_COMPILEDFILE']._serialized_end=363
  _globals['_COMPILEDFILE_SYMBOL']._serialized_start=291
  _globals['_COMPILEDFILE_SYMBOL']._serialized_end=363
# @@protoc_insertion_point(module_scope)
