# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResourcesInternal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Configuration_pb2 as Configuration__pb2
from . import Resources_pb2 as Resources__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ResourcesInternal.proto\x12\x10\x61\x61pt.pb.internal\x1a\x13\x43onfiguration.proto\x1a\x0fResources.proto\"\x97\x02\n\x0c\x43ompiledFile\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12&\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x16.aapt.pb.Configuration\x12)\n\x04type\x18\x03 \x01(\x0e\x32\x1b.aapt.pb.FileReference.Type\x12\x13\n\x0bsource_path\x18\x04 \x01(\t\x12>\n\x0f\x65xported_symbol\x18\x05 \x03(\x0b\x32%.aapt.pb.internal.CompiledFile.Symbol\x1aH\n\x06Symbol\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12\'\n\x06source\x18\x02 \x01(\x0b\x32\x17.aapt.pb.SourcePositionB\x1a\n\x18\x61ndroid.aapt.pb.internalb\x06proto3')



_COMPILEDFILE = DESCRIPTOR.message_types_by_name['CompiledFile']
_COMPILEDFILE_SYMBOL = _COMPILEDFILE.nested_types_by_name['Symbol']
CompiledFile = _reflection.GeneratedProtocolMessageType('CompiledFile', (_message.Message,), {

  'Symbol' : _reflection.GeneratedProtocolMessageType('Symbol', (_message.Message,), {
    'DESCRIPTOR' : _COMPILEDFILE_SYMBOL,
    '__module__' : 'ResourcesInternal_pb2'
    # @@protoc_insertion_point(class_scope:aapt.pb.internal.CompiledFile.Symbol)
    })
  ,
  'DESCRIPTOR' : _COMPILEDFILE,
  '__module__' : 'ResourcesInternal_pb2'
  # @@protoc_insertion_point(class_scope:aapt.pb.internal.CompiledFile)
  })
_sym_db.RegisterMessage(CompiledFile)
_sym_db.RegisterMessage(CompiledFile.Symbol)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030android.aapt.pb.internal'
  _COMPILEDFILE._serialized_start=84
  _COMPILEDFILE._serialized_end=363
  _COMPILEDFILE_SYMBOL._serialized_start=291
  _COMPILEDFILE_SYMBOL._serialized_end=363
# @@protoc_insertion_point(module_scope)
