---
general:
  # directory for unpacking. By default this is /tmp or
  # whatever the default set by the system is (for example:
  # /run/user/$UID/ )
  # tempdir: /tmp

  # Threads to use. 0 = maximum (dependent on system)
  # threads: 0
  verbose: true

  # Setting to indicate whether an error should be fatal
  # default: true
  error_fatal: true

  # Path for an ignore list, with information about files to ignore
  #ignore_list: /tmp/ignore.yaml
parsers:
  # a list of parsers that need to be ignored. Use the
  # 'pretty_name' attribute of the UnpackParser classes
  # here.
  #ignore:
    #- elf
